In [2]:
import numpy as np
import pandas as pd
import scipy, requests, codecs, os, re, nltk, itertools, csv
from sklearn.metrics.pairwise import cosine_similarity
import tensorflow as tf
from scipy.stats import spearmanr
import functools as ft
from sklearn.decomposition import PCA
from sklearn.preprocessing import normalize
import gdown


file_name = "glove_wiki_vectors.txt"
VEC_LEN = 300
glove_file = open("../glove_wiki_vectors.txt", 'r')
glove_word = {}
for line in glove_file:
    line = line.strip()
    _word = line.split(' ')
    vector = np.array([float(num) for num in _word[1:]])
    if len(vector) != VEC_LEN: 
        raise Exception("Word dimension is wrong")
    glove_word[_word[0]] = vector
glove_file.close()
print(len(glove_word))

322636


In [3]:
import sys
import gensim
import codecs
import json
from gensim.models.keyedvectors import Word2VecKeyedVectors
from gensim.models import KeyedVectors
import numpy as np
import random
import sklearn
from sklearn import model_selection
from sklearn import cluster
from sklearn import metrics
from sklearn.manifold import TSNE
from sklearn.svm import LinearSVC, SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction import DictVectorizer
import numpy as np
from docopt import docopt
import torch
from transformers import *
import pickle
from tqdm import tqdm

import scipy
from scipy import linalg
from scipy import sparse
from scipy.stats.stats import pearsonr
import tqdm
import matplotlib
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDClassifier, SGDRegressor, Perceptron, LogisticRegression


import warnings
warnings.filterwarnings("ignore")

import pickle
from collections import defaultdict, Counter
from typing import List, Dict

import torch
from torch import utils


import pandas as pd

import time
from mlxtend.math import vectorspace_orthonormalization

In [4]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
import keras

In [5]:
glove_word['he']

array([ 1.245750e-01, -4.009240e-01,  6.271400e-02,  4.111900e-01,
       -8.816970e-01,  2.350280e-01,  1.360400e-01, -2.392700e-02,
        1.160930e-01, -1.206110e-01, -1.762200e-02,  2.154890e-01,
        1.726310e-01, -4.240420e-01,  2.806960e-01, -1.301440e-01,
       -2.338660e-01,  4.867020e-01,  7.754460e-01, -2.059050e-01,
        3.617610e-01,  4.187000e-02, -2.559800e-01, -4.998360e-01,
       -1.035480e-01,  6.258390e-01, -2.862690e-01, -3.280910e-01,
       -2.078430e-01,  3.054890e-01,  1.082030e-01, -3.312780e-01,
       -2.726420e-01,  1.926860e-01,  5.072300e-02,  3.893320e-01,
        2.933890e-01, -4.360580e-01, -3.010200e-02,  3.158700e-01,
       -3.962860e-01,  4.540110e-01,  7.849120e-01,  6.861510e-01,
       -6.444350e-01,  2.352310e-01, -5.320800e-02, -2.613060e-01,
        1.339090e-01, -2.140570e-01,  1.470220e-01,  1.431780e-01,
       -1.402500e-01,  2.238600e-02, -6.906300e-02, -2.349210e-01,
        4.022160e-01, -1.911420e-01, -2.725900e-01,  8.616200e

In [6]:
all_words = list(glove_word.keys())

In [7]:
vec = glove_word['he'] - glove_word['she']

In [8]:
df = pd.DataFrame(columns = ['word','sim'])

In [9]:
np.where(np.array([1,2,2])==2)[0][0]

1

In [10]:
similarity = []

In [11]:
from scipy.spatial.distance import cosine

In [12]:
for word in all_words:
    similarity.append(1-cosine(vec, glove_word[word]))
    #df.loc[len(df.index)] = [word, similarity]
    #print(df.values.shape)

In [13]:
df['word'] = all_words

In [14]:
df['sim'] = similarity

In [15]:
df = df.sort_values(by="sim" , ascending=False)

In [16]:
df

word       sim
51069     benefices  0.285936
54251   outfielders  0.284975
28859   suspensions  0.262140
62175     uppingham  0.259404
7769          bulls  0.257339
...             ...       ...
1576        actress -0.403790
199445       wittum -0.407194
39              her -0.418087
246652       wifely -0.420689
40              she -0.427518

[322636 rows x 2 columns]

In [17]:
N = 9500

In [18]:
male_words = list(df['word'][:N])

In [19]:
female_words = list(df['word'][-N:])

In [20]:
X_train = []
Y_train = []

In [21]:
for i in range(N):
    X_train.append(glove_word[male_words[i]])
    Y_train.append(1)
    X_train.append(glove_word[female_words[i]])
    Y_train.append(0)

In [22]:
X_train = np.array(X_train)
Y_train = np.array(Y_train)

In [23]:
clf = LogisticRegression(warm_start = True, penalty = 'l2',
                         solver = "saga", multi_class = 'multinomial', fit_intercept = False,
                         verbose = 5, n_jobs = 90, random_state = 1, max_iter = 7)

        
start = time.time()
clf.fit(X_train, Y_train)
print("time: {}".format(time.time() - start))
print(clf.score(X_train, Y_train))

[Parallel(n_jobs=90)]: Using backend ThreadingBackend with 90 concurrent workers.


max_iter reached after 1 seconds
time: 0.5868015289306641
1.0


[Parallel(n_jobs=90)]: Done   1 out of   1 | elapsed:    0.6s finished


In [24]:
Y = clf.predict_proba(X_train)

In [25]:
Y

array([[1.49216341e-09, 9.99999999e-01],
       [9.98001404e-01, 1.99859592e-03],
       [1.77303085e-08, 9.99999982e-01],
       ...,
       [9.99999995e-01, 5.33623701e-09],
       [2.67024636e-04, 9.99732975e-01],
       [1.00000000e+00, 2.40800032e-14]])

In [26]:
def slice_freq(Y, interval):
    y_f = pd.Series(Y)
    a = pd.cut(y_f,interval)
    b=a.value_counts()
    frequency = b.sort_index().values
    return frequency

In [27]:
def SDR_multi(X_train, Y, K, h):
    X = X_train
    n = X.shape[0]
    d_x = X.shape[1]
    d_y = Y.shape[1]

    interval = np.linspace(np.min(Y), np.max(Y), h+1,endpoint=True)
    Gamma_PMS = np.zeros([d_x,d_x])
    for i in range(d_y):  
        freq = slice_freq(Y[:,i], interval)
        Gamma = np.zeros([d_x,d_x])
        for j in range(h):
            ph = freq[j]/n
            if ph == 0:
                mh = np.zeros(d_x)
            else:
                index = np.where((Y[:,i]>=interval[j])&(Y[:,i]<=interval[j+1]))
                mh = (1/(n*ph))*np.sum(X[index,:],0)
            Gamma = Gamma + ph*np.dot(mh.T,mh)
        la_g, v_g = np.linalg.eig(Gamma)
        la_g = la_g.real
        Gamma_PMS = Gamma_PMS + la_g[0]*Gamma
    la_PMS, v_PMS = np.linalg.eig(Gamma_PMS)
    v_PMS = v_PMS.real
    beta1 = vectorspace_orthonormalization(v_PMS[:,:K])
    #beta1 = v_PMS[:,:K]
    return np.dot(beta1,beta1.T), np.eye(d_x)-np.dot(beta1,beta1.T) 

In [28]:
def iteration_estimation_v2(X_train, Y, Iter, q, h):
    N_sample = len(X_train)
    d = X_train.shape[1]
    beta1 = np.eye(d)
    
    X_batch = X_train
    n = X_batch.shape[0]
    X = X_batch-np.mean(X_batch,0).reshape(1,d)
    Cx = np.dot(X_batch.T,X_batch)/n
    la, v = np.linalg.eig(Cx)
    la = la.real
    v = v.real
    Cx12 = np.dot(np.dot(v,np.diag(la**(0.5))),v.T)
    X_train = np.dot(X_batch,np.linalg.pinv(Cx12,rcond=1e-8))
    beta1, beta2 = SDR_multi(X_train, Y, q, h)
    if Iter == 0:
        return beta1, beta2
    else:
        for j in range(Iter):
            idx = np.random.rand(X_train.shape[0]) < 1
            X_train = np.dot(X_train,beta1)
            beta1, beta2 = SDR_multi(X_train[idx], Y[idx], q, h)
            print(np.diag(beta1)[:5])
    return beta1, beta2

In [29]:
q_vec = list(range(60,81,5))
Iter_vec = [1]
h = 100

In [30]:
for j in range(len(Iter_vec)):
    Iter = Iter_vec[j]
    #df = pd.DataFrame(index = q_vec)
    b1 = np.zeros(len(q_vec))
    b2 = np.zeros(len(q_vec))

    for k in range(len(q_vec)):
        q = q_vec[k]
        print("Iter is "+ str(Iter)+ " dim of subspace is "+ str(q))

        beta1, beta2 = iteration_estimation_v2(X_train, Y, Iter, q, h)
        df_proj = pd.DataFrame(beta1)
        df_proj.to_csv("results/"+"Iter_"+str(Iter)+'_q_'+str(q)+'_'+str(N)+"_Glove.csv")
        


Iter is 1 dim of subspace is 60
[0.2544181  0.16928745 0.19203799 0.22119565 0.30440337]
Iter is 1 dim of subspace is 65
[0.25816793 0.19148486 0.20454973 0.22904384 0.32404595]
Iter is 1 dim of subspace is 70
[0.28206085 0.19803897 0.21570116 0.282366   0.33044335]
Iter is 1 dim of subspace is 75
[0.29069778 0.22084213 0.22405737 0.29377991 0.3389129 ]
Iter is 1 dim of subspace is 80
[0.31736804 0.25666796 0.24709929 0.31160829 0.37161865]
